---
kind: pipeline
type: docker
name: review

platform:
  os: linux
  arch: amd64

steps:
- name: gofmt
  image: golang:1.13.4
  commands:
  - ./check_gofmt

trigger:
  branch:
  - master
  event:
  - pull_request

...
