name: test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - v1 # todo: delete this before releasing v1
  pull_request:
permissions:
  contents: read
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.16.x, 1.17.x]
    name: go-test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      # - name: go-test
      #   run: go test -race -v ./...
