# name: test
# on:
#   push:
#     tags:
#       - v*
#     branches:
#       - master
#       - v1 # todo: delete this before releasing v1
#   pull_request:
# jobs:
#   test:
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#         go-version: [1.16.x, 1.17.x]
#     name: test
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/setup-go@v2
#         with:
#           go-version: ${{ matrix.go-version }}
#       - uses: actions/checkout@v2
#       - name: go test 
#         run: go test -race -v ./...
